---
abstract: 'Extensible and flexible model for ElasticSearch based on Moose'
author:
  - 'Moritz Onken'
build_requires:
  File::Find: 0
  File::Temp: 0
  IO::Socket::INET: 0
  Module::Build: 0.3601
  Test::MockObject::Extends: 0
  Test::More: 0.88
  Test::Most: 0
configure_requires:
  Module::Build: 0.3601
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.112150'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: ElasticSearchX-Model
provides:
  ElasticSearchX::Model:
    file: lib/ElasticSearchX/Model.pm
    version: v0.0.2
  ElasticSearchX::Model::Bulk:
    file: lib/ElasticSearchX/Model/Bulk.pm
    version: v0.0.2
  ElasticSearchX::Model::Document:
    file: lib/ElasticSearchX/Model/Document.pm
    version: v0.0.2
  ElasticSearchX::Model::Document::Mapping:
    file: lib/ElasticSearchX/Model/Document/Mapping.pm
    version: v0.0.2
  ElasticSearchX::Model::Document::Role:
    file: lib/ElasticSearchX/Model/Document/Role.pm
    version: v0.0.2
  ElasticSearchX::Model::Document::Set:
    file: lib/ElasticSearchX/Model/Document/Set.pm
    version: v0.0.2
  ElasticSearchX::Model::Document::Trait::Attribute:
    file: lib/ElasticSearchX/Model/Document/Trait/Attribute.pm
    version: v0.0.2
  ElasticSearchX::Model::Document::Trait::Class:
    file: lib/ElasticSearchX/Model/Document/Trait/Class.pm
    version: v0.0.2
  ElasticSearchX::Model::Document::Types:
    file: lib/ElasticSearchX/Model/Document/Types.pm
    version: v0.0.2
  ElasticSearchX::Model::Index:
    file: lib/ElasticSearchX/Model/Index.pm
    version: v0.0.2
  ElasticSearchX::Model::Role:
    file: lib/ElasticSearchX/Model/Role.pm
    version: v0.0.2
  ElasticSearchX::Model::Scroll:
    file: lib/ElasticSearchX/Model/Scroll.pm
    version: v0.0.2
  ElasticSearchX::Model::Trait::Class:
    file: lib/ElasticSearchX/Model/Trait/Class.pm
    version: v0.0.2
  ElasticSearchX::Model::Tutorial:
    file: lib/ElasticSearchX/Model/Tutorial.pm
    version: v0.0.2
  ElasticSearchX::Model::Util:
    file: lib/ElasticSearchX/Model/Util.pm
    version: v0.0.2
requires:
  Carp: 0
  DateTime: 0
  DateTime::Format::Epoch::Unix: 0
  DateTime::Format::ISO8601: 0
  Digest::SHA1: 0
  ElasticSearch: 0
  ElasticSearch::ScrolledSearch: 0
  JSON: 0
  JSON::XS: 0
  List::MoreUtils: 0
  List::Util: 0
  Module::Find: 0
  Moose: 2.02
  Moose::Exporter: 0
  Moose::Role: 0
  Moose::Util::TypeConstraints: 0
  MooseX::Attribute::Deflator: v2.1.7
  MooseX::Attribute::LazyInflator::Meta::Role::Attribute: 0
  MooseX::ChainedAccessors: 0
  MooseX::Types: 0
  MooseX::Types::ElasticSearch: 0
  MooseX::Types::Moose: 0
  MooseX::Types::Structured: 0
  Scalar::Util: 0
  Sub::Exporter: 0
  Try::Tiny: 0
  strict: 0
  warnings: 0
resources:
  license: http://www.opensource.org/licenses/bsd-license.php
version: v0.0.2
