---
abstract: 'Extensible and flexible model for ElasticSearch based on Moose'
author:
  - 'Moritz Onken'
build_requires:
  File::Find: 0
  File::Temp: 0
  IO::Socket::INET: 0
  Module::Build: 0.3601
  Test::MockObject::Extends: 0
  Test::More: 0.88
  Test::Most: 0
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300006, CPAN::Meta::Converter version 2.113640'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: ElasticSearchX-Model
provides:
  ElasticSearchX::Model:
    file: lib/ElasticSearchX/Model.pm
    version: v0.0.5
  ElasticSearchX::Model::Bulk:
    file: lib/ElasticSearchX/Model/Bulk.pm
    version: v0.0.5
  ElasticSearchX::Model::Document:
    file: lib/ElasticSearchX/Model/Document.pm
    version: v0.0.5
  ElasticSearchX::Model::Document::Mapping:
    file: lib/ElasticSearchX/Model/Document/Mapping.pm
    version: v0.0.5
  ElasticSearchX::Model::Document::Role:
    file: lib/ElasticSearchX/Model/Document/Role.pm
    version: v0.0.5
  ElasticSearchX::Model::Document::Set:
    file: lib/ElasticSearchX/Model/Document/Set.pm
    version: v0.0.5
  ElasticSearchX::Model::Document::Trait::Attribute:
    file: lib/ElasticSearchX/Model/Document/Trait/Attribute.pm
    version: v0.0.5
  ElasticSearchX::Model::Document::Trait::Class:
    file: lib/ElasticSearchX/Model/Document/Trait/Class.pm
    version: v0.0.5
  ElasticSearchX::Model::Document::Types:
    file: lib/ElasticSearchX/Model/Document/Types.pm
    version: v0.0.5
  ElasticSearchX::Model::Index:
    file: lib/ElasticSearchX/Model/Index.pm
    version: v0.0.5
  ElasticSearchX::Model::Role:
    file: lib/ElasticSearchX/Model/Role.pm
    version: v0.0.5
  ElasticSearchX::Model::Scroll:
    file: lib/ElasticSearchX/Model/Scroll.pm
    version: v0.0.5
  ElasticSearchX::Model::Trait::Class:
    file: lib/ElasticSearchX/Model/Trait/Class.pm
    version: v0.0.5
  ElasticSearchX::Model::Tutorial:
    file: lib/ElasticSearchX/Model/Tutorial.pm
    version: v0.0.5
  ElasticSearchX::Model::Util:
    file: lib/ElasticSearchX/Model/Util.pm
    version: v0.0.5
requires:
  Carp: 0
  DateTime: 0
  DateTime::Format::Epoch::Unix: 0
  DateTime::Format::ISO8601: 0
  Digest::SHA1: 0
  ElasticSearch: 0
  JSON: 0
  JSON::XS: 0
  List::MoreUtils: 0
  List::Util: 0
  Module::Find: 0
  Moose: 2.02
  MooseX::Attribute::Deflator: 2.1.7
  MooseX::ChainedAccessors: 0
  MooseX::Types: 0
  MooseX::Types::ElasticSearch: 0
  MooseX::Types::Moose: 0
  MooseX::Types::Structured: 0
  Scalar::Util: 0
  Sub::Exporter: 0
  Try::Tiny: 0
resources:
  bugtracker: https://github.com/monken/p5-elasticsearch-model/issues
  repository: git://github.com/monken/p5-elasticsearch-model.git
version: 0.0.5
x_Dist_Zilla:
  plugins:
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: test
          type: requires
      name: TestRequires
      version: 4.300006
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: runtime
          type: requires
      name: RuntimeRequires
      version: 4.300006
    -
      class: Dist::Zilla::Plugin::GatherDir
      name: GatherDir
      version: 4.300006
    -
      class: Dist::Zilla::Plugin::Test::Compile
      name: Test::Compile
      version: 1.112820
    -
      class: Dist::Zilla::Plugin::HasVersionTests
      name: HasVersionTests
      version: 1.101420
    -
      class: Dist::Zilla::Plugin::KwaliteeTests
      name: KwaliteeTests
      version: 1.101420
    -
      class: Dist::Zilla::Plugin::Test::MinimumVersion
      name: Test::MinimumVersion
      version: 2.0.1
    -
      class: Dist::Zilla::Plugin::PodCoverageTests
      name: PodCoverageTests
      version: 4.300006
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: PodSyntaxTests
      version: 4.300006
    -
      class: Dist::Zilla::Plugin::ReportVersions::Tiny
      name: ReportVersions::Tiny
      version: 1.03
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: PruneCruft
      version: 4.300006
    -
      class: Dist::Zilla::Plugin::PruneFiles
      name: PruneFiles
      version: 4.300006
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: ManifestSkip
      version: 4.300006
    -
      class: Dist::Zilla::Plugin::ExtraTests
      name: ExtraTests
      version: 4.300006
    -
      class: Dist::Zilla::Plugin::NextRelease
      name: NextRelease
      version: 4.300006
    -
      class: Dist::Zilla::Plugin::PkgVersion
      name: PkgVersion
      version: 4.300006
    -
      class: Dist::Zilla::Plugin::PodWeaver
      name: PodWeaver
      version: 3.101641
    -
      class: Dist::Zilla::Plugin::Prepender
      name: Prepender
      version: 1.112280
    -
      class: Dist::Zilla::Plugin::ExecDir
      name: ExecDir
      version: 4.300006
    -
      class: Dist::Zilla::Plugin::ShareDir
      name: ShareDir
      version: 4.300006
    -
      class: Dist::Zilla::Plugin::Bugtracker
      name: Bugtracker
      version: 1.111080
    -
      class: Dist::Zilla::Plugin::Repository
      name: Repository
      version: 0.18
    -
      class: Dist::Zilla::Plugin::MetaProvides::Package
      name: MetaProvides::Package
      version: 1.12060501
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: MetaConfig
      version: 4.300006
    -
      class: Dist::Zilla::Plugin::License
      name: License
      version: 4.300006
    -
      class: Dist::Zilla::Plugin::ModuleBuild
      name: ModuleBuild
      version: 4.300006
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: MetaYAML
      version: 4.300006
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: MetaJSON
      version: 4.300006
    -
      class: Dist::Zilla::Plugin::Readme
      name: Readme
      version: 4.300006
    -
      class: Dist::Zilla::Plugin::Manifest
      name: Manifest
      version: 4.300006
    -
      class: Dist::Zilla::Plugin::CheckChangeLog
      name: CheckChangeLog
      version: 0.01
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: 4.300006
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':IncModules'
      version: 4.300006
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: 4.300006
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: 4.300006
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: 4.300006
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':MainModule'
      version: 4.300006
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: 0
    version: 4.300006
